# Generated by Django 3.1.7 on 2021-04-06 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 21, 16, 21, 237809)),
        ),
        migrations.AlterField(
            model_name='user',
            name='_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
